#  SPDX-License-Identifier: BSD-3-Clause
#  This file is part of fastrpc. It creates the fastrpc system group.
#
#Type  Name      ID       GECOS              Home directory  Shell
g      fastrpc   -        -                  -               -
